# Generated by Django 5.0.2 on 2024-02-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipocket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='price_unit',
        ),
        migrations.AddField(
            model_name='ativo',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
    ]
